config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true, length: { maximum: 4000 }

  after_save :increment_posts_comments_counter

  private

  def increment_posts_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :increment_posts_likes_counter

  private

  def increment_posts_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes

  validates :title, presence: true
  validates :title, length: { maximum: 250, too_long: 'The maximum characters allowed for a Title is 250 characters' }
  validates :text, presence: true, length: { maximum: 4000 }
  validates :comments_counter, comparison: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, comparison: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :increment_user_posts_count

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increment_user_posts_count
    user.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :likes
  has_many :comments

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    p 'create started'
    p params
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:text))
    @comment.user = @user
    @comment.post = @post
    p "got to end of variables user #{@user.name} post #{@post.text} comment on #{@comment.post.id}"

    if @comment.save
      flash[:success] = 'New Post saved successfully!'
      p @comment
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:error] = 'Post failed..'
      render :new
    end
    p params
  end

  def new
    @comment = Comment.new
    @user = current_user
    @post = Post.find(params[:post_id])
    render :new
    p params
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    create_like unless liked?
  end

  private

  def liked?
    Like.where(user_id: @user.id, post_id: @post.id).exists?
  end

  def create_like
    @like = Like.new
    @like.user_id = @user.id
    @like.post_id = params[:post_id]
    redirect_to user_post_path(@user, @post) if @like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = current_user
    @posts = Post.where(user: params[:user_id])
    @all_posts = Post.where(user: params[:user_id])
    @comments = Comment.where(post_id: params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @user = current_user
    @comments = Comment.where(post_id: params[:id])
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :text))
    @post.user = current_user

    if @post.save
      flash[:success] = 'New Post saved successfully!'
      redirect_to user_posts_path(current_user)
    else
      flash.now[:error] = 'Post failed..'
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = current_user
    @recent_posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Create New Comment</h1>
<br>
<%= render partial: "partials/comment_form", locals: {comment: @comment, user: @user, post: @post}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_comment_form.html.erb
<%= form_with model: @comment, url: "/users/#{user.id}/posts/#{post.id}/comments", method: :post, html: { class: "submit"} do |form|%>
  <%=form.label :text%>
  <%=form.text_area :text, size: "60x10"%>
  <%=form.submit%>
<% end %>

app/views/partials/_form.html.erb
<%= form_with model: @post, url: "/users/:user_id/posts", method: :post, html: { class: "submit"} do |form|%>
  <%=form.label :title%>
  <%=form.text_field :title%>
  <%=form.label :text%>
  <%=form.text_area :text, size: "60x10"%>
  <%=form.submit%>
<% end %>

app/views/partials/_post_card.html.erb
<div class='post_card'>
  <div>
  <%= link_to "Post ##{index + 1}", user_post_path(@user, post)%>
  </div>
  <div class='post_text'><%="#{post.text}"%></div>
  <div class='post_details'><%="Comments: #{post.comments_counter}, Likes: #{post.likes_counter}"%></div>
</div>

app/views/partials/_post_expanded.html.erb
<div class='detailed_post'>
<div class='post_header'>
  <div><%="Post ##{post.id} by "%><%= link_to "#{user.name}", user_path(user)%></div>
  <div><%="Comments: #{post.comments_counter}, Likes: #{post.likes_counter}"%></div>
</div>
<%="#{post.text}"%>
</div>
<div>

app/views/partials/_user_card.html.erb
<div class='user_card'>
<div class='img_placeholder'></div>
<%= link_to "#{user.name}", user_path(user) %>
<%="Number of Posts: #{user.posts_counter}"%>
</div>

app/views/posts/index.html.erb
<div class='user_body'>
<%=render partial: 'partials/user_card', locals: { user: @user }%>

<div class='top_post_list'>
  <%@all_posts.each_with_index do |post, index|%>
  <%=render partial: 'partials/post_card', locals: { post: post, index: index }%> 
  <%post.recent_comments.each do |comment|%>
      <div><%="#{comment.user.name}: #{comment.text}"%></div>
    <%end%>
  <%end%>
  <button type='button'><%= link_to "Create new post", new_user_post_path(@user) %></button>
</div>
</div>

app/views/posts/new.html.erb
<h1>Create New Post</h1>
<br>
<%= render partial: "partials/form", locals: {post: @post}%>

app/views/posts/show.html.erb
<div class="post_body">
  <%=render partial: 'partials/post_expanded', locals: { post:@post, user: @user }%>
  <%= form_with url: "/users/#{@user.id}/posts/#{@post.id}/likes" do |like|%>
  <%=like.submit "Like Post"%>
  <div class="post_comments">
  <div>Comments </div>
    <%@comments.each do |comment|%>
      <div><%="#{comment.user.name}: #{comment.text}"%></div>
    <%end%>
  </div>
<% end %>
<button type='button'><%= link_to "Comment", new_user_post_comment_path(@user, @post) %></button>
</div>

app/views/users/index.html.erb
<% @users.each do |user|%>
<%=render partial: 'partials/user_card', locals: { user: user }%>
<%end%>

app/views/users/show.html.erb
<div class='user_body'>
<%=render partial: 'partials/user_card', locals: { user: @user }%>

<div class='bio'>
  <p>Bio</p>
  <div class='bio_text'><%=@user.bio%></div>
</div>

<div class='top_post_list'>
  <%@recent_posts.each_with_index do |post, index|%>
  <%=render partial: 'partials/post_card', locals: { post: post, index: index, user: @user }%> 
  <%end%>
  <button type='button'><%= link_to "See all posts", user_posts_path(@user) %></button>
<div>
</div>